workflows:
  ios-app:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/pokerogue-ios-wrapper.xcworkspace"
        XCODE_SCHEME: "pokerogue-ios-wrapper"
      xcode: 15.0
      node: 18
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Build iOS app
        script: |
          npx expo prebuild --platform ios
          npx expo run:ios --no-install
    artifacts:
      - build/ios/**/*.ipa
